/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#define SYSCTL_RCGC2_R *((volatile uint32_t*)(0x400FE108))
#define PORT_F_DIR *((volatile uint32_t*)(0x40025400))
#define PORTF_DEN_R *((volatile uint32_t*)(0x4002551C))
#define PORTF_DATA_R *((volatile uint32_t*)(0x400253FC))


int main(void)
{
	int i =0;
	volatile uint32_t delay_count =0;
	SYSCTL_RCGC2_R = 0x20;
	for(delay_count=0; delay_count<200; delay_count++);
	PORT_F_DIR |= 1<<3;
	PORTF_DEN_R |= 1<<3;
	while(1)
	{
		PORTF_DATA_R |= (1<<3);
		for(i=0;i<200000;i++);
		PORTF_DATA_R &= ~(1<<3);
		for(i=0;i<200000;i++);
	}
	return 0;
}
